import { createCanvas } from 'canvas';

export default {
    name: 'photocreate',
    description: 'Generate a simple image with text',
    async execute(sock, m, { args, botName }) {
        if (args.length === 0) return await sock.sendMessage(m.key.remoteJid, { text: 'Please provide text for the image.' });

        const text = args.join(' ');
        const canvas = createCanvas(800, 400);
        const ctx = canvas.getContext('2d');

        // Background
        ctx.fillStyle = '#1e293b';
        ctx.fillRect(0, 0, 800, 400);

        // Border
        ctx.strokeStyle = '#38bdf8';
        ctx.lineWidth = 10;
        ctx.strokeRect(20, 20, 760, 360);

        // Text
        ctx.fillStyle = '#ffffff';
        ctx.font = 'bold 50px Arial';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillText(text, 400, 200);

        // Bot Seal
        ctx.font = '20px Arial';
        ctx.fillStyle = '#38bdf8';
        ctx.fillText(`Generated by ${botName}`, 400, 340);

        const buffer = canvas.toBuffer('image/png');
        await sock.sendMessage(m.key.remoteJid, {
            image: buffer,
            caption: `🎨 *WarriorBot Creation*`
        });
    }
};
